build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Mehmet Consent Baller - QA Lead"
    email: "mBaller@hotmail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267