build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Mahmut Anass Literate - Developer"
    email: "mliterate@hotmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934