build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Esra Magnificant National - Product Owner"
    email: "esramil@garanti.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956